#!/bin/bash

. /config/.donoteditthisfile.conf

if [ "$VALIDATION" = "duckdns" ]; then
	curl https://www.duckdns.org/update?domains=${CERTBOT_DOMAIN}\&token=${ORIGDUCKDNSTOKEN}\&txt=${CERTBOT_VALIDATION}
elif [ "$VALIDATION" = "dns-alias" ]; then
	curl https://www.duckdns.org/update?domains=${ORIGALIASURL}\&token=${ORIGDUCKDNSTOKEN}\&txt=${CERTBOT_VALIDATION}
fi

echo "sleeping 60"
sleep 60
