#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/crontabs

## root
# if crontabs do not exist in config
if [[ ! -f /config/crontabs/root ]]; then
    # copy crontab from system
    if crontab -l -u root; then
        crontab -l -u root >/config/crontabs/root
    fi

    # if crontabs still do not exist in config (were not copied from system)
    # copy crontab from included defaults (using -n, do not overwrite an existing file)
    cp -n /etc/crontabs/root /config/crontabs/
fi
# set permissions and import user crontabs
lsiown root:root /config/crontabs/root
crontab -u root /config/crontabs/root

## abc
# if crontabs do not exist in config
if [[ ! -f /config/crontabs/abc ]]; then
    # copy crontab from system
    if crontab -l -u abc; then
        crontab -l -u abc >/config/crontabs/abc
    fi

    # if crontabs still do not exist in config (were not copied from system)
    # copy crontab from included defaults (using -n, do not overwrite an existing file)
    cp -n /etc/crontabs/abc /config/crontabs/
fi
# set permissions and import user crontabs
lsiown abc:abc /config/crontabs/abc
crontab -u abc /config/crontabs/abc
