#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# if root crontabs do not exist in config
# copy root crontab from system
if [[ ! -f /config/crontabs/root ]] && crontab -l -u root; then
    crontab -l -u root >/config/crontabs/root
fi

# if root crontabs still do not exist in config (were not copied from system)
# copy root crontab from included defaults
if [[ ! -f /config/crontabs/root ]]; then
    cp /etc/crontabs/root /config/crontabs/
fi

# if abc crontabs do not exist in config
# copy abc crontab from system
if [[ ! -f /config/crontabs/abc ]] && crontab -l -u abc; then
    crontab -l -u abc >/config/crontabs/abc
fi

# if abc crontabs still do not exist in config (were not copied from system)
# copy abc crontab from included defaults
if [[ ! -f /config/crontabs/abc ]]; then
    cp /etc/crontabs/abc /config/crontabs/
fi

# set permissions on crontabs
lsiown root:root \
    /config/crontabs/root
lsiown abc:abc \
    /config/crontabs/abc

# import user crontabs
crontab -u root /config/crontabs/root
crontab -u abc /config/crontabs/abc
