#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
. /config/.donoteditthisfile.conf

if [[ ! "${ORIGVALIDATION}" = "dns" ]] && [[ ! "${ORIGVALIDATION}" = "duckdns" ]]; then
    if pgrep -f "nginx:" >/dev/null; then
        s6-svc -d /run/service/svc-nginx
    fi
fi
