#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders and links
mkdir -p \
    /config/{fail2ban,dns-conf} \
    /config/etc/letsencrypt/renewal-hooks \
    /config/log/{fail2ban,letsencrypt,nginx} \
    /config/nginx/proxy-confs \
    /run/fail2ban \
    /tmp/letsencrypt

