#!/usr/bin/with-contenv bash

# make our folders and links
mkdir -p \
    /config/{fail2ban,crontabs,dns-conf} \
    /config/etc/letsencrypt \
    /config/log/{fail2ban,letsencrypt,nginx} \
    /config/nginx/proxy-confs \
    /var/run/fail2ban
rm -rf /etc/letsencrypt
ln -s /config/etc/letsencrypt /etc/letsencrypt
