#!/usr/bin/with-contenv bash

# copy default config files if they don't exist
if [[ ! -f /config/nginx/error_pages.conf ]]; then
    cp /defaults/nginx/error_pages.conf.sample /config/nginx/error_pages.conf
fi
if [[ ! -f /config/nginx/proxy.conf ]]; then
    cp /defaults/nginx/proxy.conf.sample /config/nginx/proxy.conf
fi
